ANIME_DATA = [
    {
        "title_ru": "Атака титанов",
        "title_en": "Attack on Titan",
        "description": "Человечество борется за выживание за стенами, защищаясь от титанов.",
        "genres": ["action", "drama", "fantasy"],
        "year": 2013,
        "rating": 9.1,
    },
    {
        "title_ru": "Тетрадь смерти",
        "title_en": "Death Note",
        "description": "Школьник находит тетрадь, позволяющую убивать, и вступает в дуэль умов с детективом L.",
        "genres": ["thriller", "mystery", "supernatural"],
        "year": 2006,
        "rating": 9.0,
    },
    {
        "title_ru": "Стальной алхимик: Братство",
        "title_en": "Fullmetal Alchemist: Brotherhood",
        "description": "Братья Элрики ищут философский камень, чтобы вернуть утраченные тела.",
        "genres": ["adventure", "action", "fantasy"],
        "year": 2009,
        "rating": 9.2,
    },
    {
        "title_ru": "Наруто",
        "title_en": "Naruto",
        "description": "Юный ниндзя мечтает стать хокаге и получить признание деревни.",
        "genres": ["action", "adventure", "shounen"],
        "year": 2002,
        "rating": 8.4,
    },
    {
        "title_ru": "Наруто: Ураганные хроники",
        "title_en": "Naruto Shippuden",
        "description": "Продолжение пути Наруто, более взрослые испытания и войны шиноби.",
        "genres": ["action", "adventure", "shounen"],
        "year": 2007,
        "rating": 8.7,
    },
    {
        "title_ru": "Ван-Пис",
        "title_en": "One Piece",
        "description": "Луффи собирает команду пиратов и ищет легендарное сокровище One Piece.",
        "genres": ["adventure", "comedy", "shounen"],
        "year": 1999,
        "rating": 8.9,
    },
    {
        "title_ru": "Клинок, рассекающий демонов",
        "title_en": "Demon Slayer",
        "description": "Тандзиро вступает в корпус истребителей демонов, чтобы спасти сестру.",
        "genres": ["action", "fantasy", "shounen"],
        "year": 2019,
        "rating": 8.7,
    },
    {
        "title_ru": "Магическая битва",
        "title_en": "Jujutsu Kaisen",
        "description": "Итадори поглощает проклятый палец и попадает в мир магов.",
        "genres": ["action", "supernatural", "shounen"],
        "year": 2020,
        "rating": 8.6,
    },
    {
        "title_ru": "Человек-бензопила",
        "title_en": "Chainsaw Man",
        "description": "Дэндзи становится гибридом человека и демона бензопилы.",
        "genres": ["action", "dark", "supernatural"],
        "year": 2022,
        "rating": 8.5,
    },
    {
        "title_ru": "Поднятие уровня в одиночку",
        "title_en": "Solo Leveling",
        "description": "Слабый охотник получает систему прокачки и становится сильнейшим.",
        "genres": ["action", "fantasy", "adventure"],
        "year": 2024,
        "rating": 8.8,
    },
    {
        "title_ru": "Монолог фармацевта",
        "title_en": "The Apothecary Diaries",
        "description": "Маомао расследует дворцовые интриги, используя знания фармацевтики.",
        "genres": ["mystery", "drama", "historical"],
        "year": 2023,
        "rating": 8.8,
    },
    {
        "title_ru": "Госпожа Кагуя: в любви как на войне",
        "title_en": "Kaguya-sama: Love Is War",
        "description": "Два гения пытаются заставить друг друга признаться в любви.",
        "genres": ["comedy", "romance", "school"],
        "year": 2019,
        "rating": 8.7,
    },
    {
        "title_ru": "Твоё имя",
        "title_en": "Your Name",
        "description": "Парень и девушка загадочно меняются телами и ищут друг друга.",
        "genres": ["romance", "drama", "supernatural"],
        "year": 2016,
        "rating": 8.9,
    },
    {
        "title_ru": "Форма голоса",
        "title_en": "A Silent Voice",
        "description": "История искупления бывшего хулигана и глухой девушки.",
        "genres": ["drama", "romance", "school"],
        "year": 2016,
        "rating": 8.9,
    },
    {
        "title_ru": "Унесённые призраками",
        "title_en": "Spirited Away",
        "description": "Тихиро попадает в мир духов и должна спасти родителей.",
        "genres": ["fantasy", "adventure", "family"],
        "year": 2001,
        "rating": 8.8,
    },
    {
        "title_ru": "Ходячий замок",
        "title_en": "Howl's Moving Castle",
        "description": "Софи оказывается под проклятием и встречает мага Хаула.",
        "genres": ["fantasy", "romance", "adventure"],
        "year": 2004,
        "rating": 8.7,
    },
    {
        "title_ru": "Вайолет Эвергарден",
        "title_en": "Violet Evergarden",
        "description": "Бывшая солдатка учится понимать чувства людей через письма.",
        "genres": ["drama", "slice of life", "romance"],
        "year": 2018,
        "rating": 8.8,
    },
    {
        "title_ru": "Реинкарнация безработного",
        "title_en": "Mushoku Tensei",
        "description": "Мужчина перерождается в магическом мире и пытается прожить жизнь заново.",
        "genres": ["fantasy", "adventure", "isekai"],
        "year": 2021,
        "rating": 8.6,
    },
    {
        "title_ru": "О моём перерождении в слизь",
        "title_en": "That Time I Got Reincarnated as a Slime",
        "description": "Обычный человек перерождается в слизь и строит собственное королевство.",
        "genres": ["fantasy", "isekai", "adventure"],
        "year": 2018,
        "rating": 8.2,
    },
    {
        "title_ru": "Re:Zero. Жизнь с нуля в альтернативном мире",
        "title_en": "Re:Zero − Starting Life in Another World",
        "description": "Субару получает способность возвращаться после смерти и спасает друзей.",
        "genres": ["fantasy", "isekai", "drama"],
        "year": 2016,
        "rating": 8.3,
    },
    {
        "title_ru": "Код Гиас",
        "title_en": "Code Geass",
        "description": "Лелуш получает силу абсолютного приказа и начинает революцию.",
        "genres": ["mecha", "thriller", "drama"],
        "year": 2006,
        "rating": 8.9,
    },
    {
        "title_ru": "Евангелион",
        "title_en": "Neon Genesis Evangelion",
        "description": "Подростки пилотируют биомехов, сражаясь с ангелами.",
        "genres": ["mecha", "psychological", "drama"],
        "year": 1995,
        "rating": 8.4,
    },
    {
        "title_ru": "Ковбой Бибоп",
        "title_en": "Cowboy Bebop",
        "description": "Команда охотников за головами путешествует по космосу.",
        "genres": ["sci-fi", "action", "drama"],
        "year": 1998,
        "rating": 8.9,
    },
    {
        "title_ru": "Самурай Чамплу",
        "title_en": "Samurai Champloo",
        "description": "Трое спутников ищут самурая, пахнущего подсолнухами.",
        "genres": ["action", "adventure", "historical"],
        "year": 2004,
        "rating": 8.5,
    },
    {
        "title_ru": "Дороро",
        "title_en": "Dororo",
        "description": "Юноша, лишённый частей тела демонами, возвращает себя по кусочкам.",
        "genres": ["action", "historical", "dark"],
        "year": 2019,
        "rating": 8.3,
    },
    {
        "title_ru": "Семья шпиона",
        "title_en": "Spy x Family",
        "description": "Шпион, убийца и телепатка изображают идеальную семью.",
        "genres": ["comedy", "action", "family"],
        "year": 2022,
        "rating": 8.6,
    },
    {
        "title_ru": "Обещанный Неверленд",
        "title_en": "The Promised Neverland",
        "description": "Дети узнают страшную тайну приюта и готовят побег.",
        "genres": ["thriller", "mystery", "dark"],
        "year": 2019,
        "rating": 8.5,
    },
    {
        "title_ru": "Парад смерти",
        "title_en": "Death Parade",
        "description": "После смерти люди проходят игры, раскрывающие их истинную сущность.",
        "genres": ["psychological", "mystery", "drama"],
        "year": 2015,
        "rating": 8.2,
    },
    {
        "title_ru": "Монстр",
        "title_en": "Monster",
        "description": "Хирург спасает ребёнка, который вырастает серийным убийцей.",
        "genres": ["thriller", "psychological", "drama"],
        "year": 2004,
        "rating": 9.0,
    },
    {
        "title_ru": "Психопаспорт",
        "title_en": "Psycho-Pass",
        "description": "Антиутопия, где преступность предсказывается алгоритмами.",
        "genres": ["sci-fi", "thriller", "action"],
        "year": 2012,
        "rating": 8.3,
    },
    {
        "title_ru": "Врата Штейна",
        "title_en": "Steins;Gate",
        "description": "Группа друзей случайно изобретает способ отправки сообщений в прошлое.",
        "genres": ["sci-fi", "thriller", "drama"],
        "year": 2011,
        "rating": 9.0,
    },
    {
        "title_ru": "Хайкью!!",
        "title_en": "Haikyuu!!",
        "description": "Школьная волейбольная команда борется за путь к национальному турниру.",
        "genres": ["sports", "comedy", "school"],
        "year": 2014,
        "rating": 8.7,
    },
    {
        "title_ru": "Блю Лок",
        "title_en": "Blue Lock",
        "description": "Амбициозный проект по созданию лучшего нападающего Японии.",
        "genres": ["sports", "drama", "shounen"],
        "year": 2022,
        "rating": 8.3,
    },
]

QUOTES = [
    "Люди живут, чтобы быть счастливыми. — Юкино Миядзава",
    "Если проиграл, это не значит, что всё кончено. — Наруто Удзумаки",
    "Сила не в том, чтобы побеждать, а в том, чтобы не сдаваться. — Эдвард Элрик",
    "Человек умирает, когда его забывают. — Др. Хилулук",
    "Страх — это свобода. — Акира Фудо",
    "Только тот, кто готов к боли, способен на рост. — Канэки Кэн",
    "Иногда нужно потерять всё, чтобы понять ценность жизни. — Вайолет",
    "Чудеса случаются, когда ты действуешь. — Окабэ Ринтаро",
    "Сердце делает нас людьми. — Альфонс Элрик",
    "Даже в темноте есть путь вперёд. — Леви Аккерман",
]

MEMES = [
    "Когда сказал 'ещё одну серию' в 2:00 и уже 6:45.",
    "Составил план на день, но вышел новый сезон исекая.",
    "Ищу лёгкое аниме перед сном — включаю психологический триллер.",
    "Думал, что это филлер. Через 3 серии: 'где награды за боль?'",
    "Просто хотел проверить рейтинг, а начал марафон на 120 серий.",
]
