import json
from urllib.parse import quote_plus


RAW_ANIME = [
    ("Атака титанов", "Attack on Titan", 2013, "action,fantasy,drama"),
    ("Тетрадь смерти", "Death Note", 2006, "thriller,mystery,supernatural"),
    ("Стальной алхимик: Братство", "Fullmetal Alchemist: Brotherhood", 2009, "adventure,action,fantasy"),
    ("Наруто", "Naruto", 2002, "action,adventure,shounen"),
    ("Наруто: Ураганные хроники", "Naruto Shippuden", 2007, "action,adventure,shounen"),
    ("Ван-Пис", "One Piece", 1999, "adventure,comedy,shounen"),
    ("Блич", "Bleach", 2004, "action,supernatural,shounen"),
    ("Блич: Тысячелетняя кровавая война", "Bleach: Thousand-Year Blood War", 2022, "action,supernatural,shounen"),
    ("Клинок, рассекающий демонов", "Demon Slayer", 2019, "action,fantasy,shounen"),
    ("Магическая битва", "Jujutsu Kaisen", 2020, "action,supernatural,shounen"),
    ("Человек-бензопила", "Chainsaw Man", 2022, "action,dark,supernatural"),
    ("Поднятие уровня в одиночку", "Solo Leveling", 2024, "action,fantasy,adventure"),
    ("Монолог фармацевта", "The Apothecary Diaries", 2023, "mystery,drama,historical"),
    ("Госпожа Кагуя: в любви как на войне", "Kaguya-sama: Love Is War", 2019, "comedy,romance,school"),
    ("Твоё имя", "Your Name", 2016, "romance,drama,supernatural"),
    ("Форма голоса", "A Silent Voice", 2016, "drama,romance,school"),
    ("Унесённые призраками", "Spirited Away", 2001, "fantasy,adventure,family"),
    ("Ходячий замок", "Howl's Moving Castle", 2004, "fantasy,romance,adventure"),
    ("Вайолет Эвергарден", "Violet Evergarden", 2018, "drama,slice of life,romance"),
    ("Реинкарнация безработного", "Mushoku Tensei", 2021, "fantasy,adventure,isekai"),
    ("О моём перерождении в слизь", "That Time I Got Reincarnated as a Slime", 2018, "fantasy,isekai,adventure"),
    ("Re:Zero. Жизнь с нуля в альтернативном мире", "Re:Zero", 2016, "fantasy,isekai,drama"),
    ("Код Гиас", "Code Geass", 2006, "mecha,thriller,drama"),
    ("Евангелион", "Neon Genesis Evangelion", 1995, "mecha,psychological,drama"),
    ("Ковбой Бибоп", "Cowboy Bebop", 1998, "sci-fi,action,drama"),
    ("Самурай Чамплу", "Samurai Champloo", 2004, "action,adventure,historical"),
    ("Дороро", "Dororo", 2019, "action,historical,dark"),
    ("Семья шпиона", "Spy x Family", 2022, "comedy,action,family"),
    ("Обещанный Неверленд", "The Promised Neverland", 2019, "thriller,mystery,dark"),
    ("Парад смерти", "Death Parade", 2015, "psychological,mystery,drama"),
    ("Монстр", "Monster", 2004, "thriller,psychological,drama"),
    ("Психопаспорт", "Psycho-Pass", 2012, "sci-fi,thriller,action"),
    ("Врата Штейна", "Steins;Gate", 2011, "sci-fi,thriller,drama"),
    ("Хайкью!!", "Haikyuu!!", 2014, "sports,comedy,school"),
    ("Блю Лок", "Blue Lock", 2022, "sports,drama,shounen"),
    ("Баскетбол Куроко", "Kuroko's Basketball", 2012, "sports,comedy,school"),
    ("Слэм-данк", "Slam Dunk", 1993, "sports,comedy,school"),
    ("Боку но Хиро Академия", "My Hero Academia", 2016, "action,superhero,school"),
    ("Чёрный клевер", "Black Clover", 2017, "action,fantasy,adventure"),
    ("Синий экзорцист", "Blue Exorcist", 2011, "action,supernatural,school"),
    ("Сага о Винланде", "Vinland Saga", 2019, "action,adventure,historical"),
    ("Берсерк", "Berserk", 1997, "action,dark,fantasy"),
    ("Охотник х Охотник", "Hunter x Hunter", 2011, "adventure,action,shounen"),
    ("Семь смертных грехов", "The Seven Deadly Sins", 2014, "action,fantasy,adventure"),
    ("Фейри Тейл", "Fairy Tail", 2009, "action,adventure,fantasy"),
    ("Эдем: Восток", "Eden of the East", 2009, "mystery,thriller,romance"),
    ("Гуррен-Лаганн", "Gurren Lagann", 2007, "mecha,action,adventure"),
    ("86", "Eighty-Six", 2021, "mecha,drama,sci-fi"),
    ("Альдноа Зеро", "Aldnoah.Zero", 2014, "mecha,action,sci-fi"),
    ("Макросс Фронтир", "Macross Frontier", 2008, "mecha,romance,sci-fi"),
    ("Врата", "Gate", 2015, "fantasy,action,military"),
    ("Лог Горизонт", "Log Horizon", 2013, "fantasy,isekai,adventure"),
    ("Повелитель", "Overlord", 2015, "fantasy,isekai,action"),
    ("Коносуба", "KonoSuba", 2016, "comedy,isekai,fantasy"),
    ("No Game No Life", "No Game No Life", 2014, "fantasy,isekai,comedy"),
    ("Сатана на подработке", "The Devil Is a Part-Timer!", 2013, "comedy,fantasy,romance"),
    ("Торадора!", "Toradora!", 2008, "romance,comedy,school"),
    ("Твоя апрельская ложь", "Your Lie in April", 2014, "romance,drama,music"),
    ("Кланнад", "Clannad", 2007, "romance,drama,school"),
    ("Кланнад: После истории", "Clannad After Story", 2008, "romance,drama,school"),
    ("Не издевайся, Нагаторо", "Don't Toy with Me, Miss Nagatoro", 2021, "romance,comedy,school"),
    ("Эта фарфоровая кукла влюбилась", "My Dress-Up Darling", 2022, "romance,comedy,school"),
    ("Хоримия", "Horimiya", 2021, "romance,comedy,school"),
    ("Пять невест", "The Quintessential Quintuplets", 2019, "romance,comedy,school"),
    ("Президент студсовета — горничная", "Maid Sama!", 2010, "romance,comedy,school"),
    ("Крутой учитель Онидзука", "Great Teacher Onizuka", 1999, "comedy,school,drama"),
    ("Сакамото к вашим услугам", "Haven't You Heard? I'm Sakamoto", 2016, "comedy,school,slice of life"),
    ("Гинтама", "Gintama", 2006, "comedy,action,sci-fi"),
    ("Saiki Kusuo no Psi-nan", "The Disastrous Life of Saiki K.", 2016, "comedy,school,supernatural"),
    ("Повседневная жизнь старшеклассников", "Daily Lives of High School Boys", 2012, "comedy,school,slice of life"),
    ("Nichijou", "Nichijou", 2011, "comedy,school,slice of life"),
    ("Бездомный бог", "Noragami", 2014, "action,supernatural,comedy"),
    ("Пожиратель душ", "Soul Eater", 2008, "action,supernatural,comedy"),
    ("Пламенная бригада пожарных", "Fire Force", 2019, "action,supernatural,shounen"),
    ("Доктор Стоун", "Dr. Stone", 2019, "adventure,sci-fi,shounen"),
    ("Обещанный цветок", "Maquia: When the Promised Flower Blooms", 2018, "drama,fantasy,romance"),
    ("Дитя погоды", "Weathering with You", 2019, "romance,drama,supernatural"),
    ("5 сантиметров в секунду", "5 Centimeters per Second", 2007, "romance,drama"),
    ("Девочка, покорившая время", "The Girl Who Leapt Through Time", 2006, "romance,sci-fi,drama"),
    ("Принцесса Мононоке", "Princess Mononoke", 1997, "fantasy,adventure,drama"),
    ("Навсикая из долины ветров", "Nausicaä of the Valley of the Wind", 1984, "fantasy,adventure,sci-fi"),
    ("Мой сосед Тоторо", "My Neighbor Totoro", 1988, "family,fantasy,adventure"),
    ("Ведьмина служба доставки", "Kiki's Delivery Service", 1989, "fantasy,family,adventure"),
    ("Замок в небе", "Castle in the Sky", 1986, "fantasy,adventure"),
    ("Поньо", "Ponyo", 2008, "family,fantasy,adventure"),
    ("Паприка", "Paprika", 2006, "sci-fi,psychological,mystery"),
    ("Идеальная грусть", "Perfect Blue", 1998, "thriller,psychological,mystery"),
    ("Агент паранойи", "Paranoia Agent", 2004, "psychological,mystery,thriller"),
    ("Мадока Магика", "Puella Magi Madoka Magica", 2011, "fantasy,psychological,drama"),
    ("Made in Abyss", "Made in Abyss", 2017, "adventure,fantasy,dark"),
    ("Без игры нет жизни: Ноль", "No Game No Life: Zero", 2017, "fantasy,romance,drama"),
    ("Башня Бога", "Tower of God", 2020, "action,fantasy,adventure"),
    ("Бог старшей школы", "The God of High School", 2020, "action,supernatural,school"),
    ("Ноблес", "Noblesse", 2020, "action,supernatural,school"),
    ("To Your Eternity", "To Your Eternity", 2021, "drama,fantasy,adventure"),
    ("Путешествие Кино", "Kino's Journey", 2003, "adventure,drama,philosophical"),
    ("Мастер Муси", "Mushishi", 2005, "slice of life,supernatural,mystery"),
    ("Нана", "Nana", 2006, "drama,romance,music"),
    ("Бек", "BECK", 2004, "music,drama,comedy"),
    ("Кэй-Он!", "K-On!", 2009, "music,comedy,slice of life"),
    ("Carole & Tuesday", "Carole & Tuesday", 2019, "music,drama,sci-fi"),
    ("Дюрарара!!", "Durarara!!", 2010, "action,mystery,supernatural"),
    ("Баккано!", "Baccano!", 2007, "action,mystery,supernatural"),
    ("Триган", "Trigun", 1998, "action,comedy,sci-fi"),
    ("Триган Стампид", "Trigun Stampede", 2023, "action,sci-fi,adventure"),
    ("Хеллсинг Ultimate", "Hellsing Ultimate", 2006, "action,supernatural,dark"),
    ("Бугипоп и другие", "Boogiepop and Others", 2019, "mystery,psychological,supernatural"),
    ("Another", "Another", 2012, "horror,mystery,school"),
    ("Когда плачут цикады", "Higurashi: When They Cry", 2006, "horror,mystery,psychological"),
    ("Паразит", "Parasyte", 2014, "action,horror,sci-fi"),
    ("Токийский гуль", "Tokyo Ghoul", 2014, "action,dark,supernatural"),
    ("Эльфийская песнь", "Elfen Lied", 2004, "horror,drama,psychological"),
    ("Erased", "Erased", 2016, "mystery,thriller,drama"),
    ("Терраформирование", "Terra Formars", 2014, "action,sci-fi,horror"),
    ("Акаме га Килл!", "Akame ga Kill!", 2014, "action,dark,fantasy"),
    ("Fate/Zero", "Fate/Zero", 2011, "action,fantasy,supernatural"),
    ("Fate/stay night: Unlimited Blade Works", "Fate/stay night: Unlimited Blade Works", 2014, "action,fantasy,supernatural"),
    ("Судьба: Ночь схватки", "Fate/stay night", 2006, "action,fantasy,supernatural"),
    ("Сад грешников", "The Garden of Sinners", 2007, "mystery,supernatural,thriller"),
    ("Класс превосходства", "Classroom of the Elite", 2017, "school,thriller,drama"),
    ("Игра друзей", "Tomodachi Game", 2022, "thriller,psychological,school"),
    ("Легенда о героях Галактики", "Legend of the Galactic Heroes", 1988, "sci-fi,drama,military"),
    ("Волчий дождь", "Wolf's Rain", 2003, "adventure,drama,fantasy"),
    ("Тёмный дворецкий", "Black Butler", 2008, "mystery,supernatural,comedy"),
    ("Синий период", "Blue Period", 2021, "drama,school,slice of life"),
    ("Бармен", "Bartender", 2006, "slice of life,drama"),
    ("Ресторан из другого мира", "Restaurant to Another World", 2017, "fantasy,slice of life,comedy"),
    ("Лагерь на свежем воздухе", "Laid-Back Camp", 2018, "slice of life,comedy"),
    ("Баракамон", "Barakamon", 2014, "comedy,slice of life"),
    ("Серебряная ложка", "Silver Spoon", 2013, "comedy,school,slice of life"),
    ("Клетки за работой", "Cells at Work!", 2018, "comedy,educational,action"),
    ("Адский рай", "Hell's Paradise", 2023, "action,dark,fantasy"),
    ("Кайдзю №8", "Kaiju No. 8", 2024, "action,sci-fi,shounen"),
    ("Фрирен, провожающая в последний путь", "Frieren: Beyond Journey's End", 2023, "fantasy,adventure,drama"),
    ("Опасность в моём сердце", "The Dangers in My Heart", 2023, "romance,comedy,school"),
    ("Инсомния после школы", "Insomniacs After School", 2023, "romance,drama,school"),
    ("Невеста чародея", "The Ancient Magus' Bride", 2017, "fantasy,romance,drama"),
    ("Плод эволюции", "The Fruit of Evolution", 2021, "comedy,isekai,fantasy"),
    ("Герой щита", "The Rising of the Shield Hero", 2019, "fantasy,isekai,action"),
    ("Арифурэта", "Arifureta", 2019, "fantasy,isekai,action"),
    ("Внук мудреца", "Wise Man's Grandchild", 2019, "fantasy,isekai,comedy"),
    ("Как и ожидалось, моя школьная романтическая жизнь не удалась", "My Teen Romantic Comedy SNAFU", 2013, "romance,comedy,school"),
    ("Рандеву с жизнью", "Date A Live", 2013, "romance,comedy,supernatural"),
    ("Любовные неприятности", "To LOVE-Ru", 2008, "comedy,romance,school"),
    ("Чудачества любви не помеха", "Love, Chunibyo & Other Delusions", 2012, "romance,comedy,school"),
    ("Бессонница после школы", "Insomniacs After School", 2023, "romance,drama,school"),
    ("Золотая пора", "Golden Time", 2013, "romance,drama,comedy"),
    ("Сад изящных слов", "The Garden of Words", 2013, "romance,drama"),
    ("Звучи, эуфониум!", "Sound! Euphonium", 2015, "music,drama,school"),
    ("Free!", "Free!", 2013, "sports,school,drama"),
    ("Юрий на льду", "Yuri on Ice", 2016, "sports,drama,romance"),
    ("Ace of Diamond", "Ace of Diamond", 2013, "sports,school,drama"),
    ("Major", "Major", 2004, "sports,drama"),
    ("Принц тенниса", "The Prince of Tennis", 2001, "sports,school"),
    ("Initial D", "Initial D", 1998, "sports,action,drama"),
    ("Капитан Цубаса", "Captain Tsubasa", 1983, "sports,school,drama"),
    ("Токийские мстители", "Tokyo Revengers", 2021, "action,drama,school"),
    ("Великий из бродячих псов", "Bungo Stray Dogs", 2016, "action,mystery,supernatural"),
    ("Моб Психо 100", "Mob Psycho 100", 2016, "action,comedy,supernatural"),
    ("One-Punch Man", "One-Punch Man", 2015, "action,comedy,superhero"),
    ("Доктор Рамунэ", "Dr. Ramune", 2021, "supernatural,comedy,mystery"),
    ("Триплексоголик", "xxxHOLiC", 2006, "supernatural,mystery,comedy"),
    ("Кровь+", "Blood+", 2005, "action,horror,supernatural"),
    ("Claymore", "Claymore", 2007, "action,fantasy,dark"),
    ("Убийца гоблинов", "Goblin Slayer", 2018, "action,fantasy,dark"),
    ("Волчица и пряности", "Spice and Wolf", 2008, "romance,fantasy,adventure"),
    ("Волчица и пряности (2024)", "Spice and Wolf: Merchant Meets the Wise Wolf", 2024, "romance,fantasy,adventure"),
    ("Рыцарь-вампир", "Vampire Knight", 2008, "romance,supernatural,school"),
    ("Ди: Охотник на вампиров", "Vampire Hunter D", 1985, "action,horror,fantasy"),
    ("Драгонболл", "Dragon Ball", 1986, "action,adventure,comedy"),
    ("Драгонболл Z", "Dragon Ball Z", 1989, "action,adventure,shounen"),
    ("Драгонболл Супер", "Dragon Ball Super", 2015, "action,adventure,shounen"),
]


def _make_watch_urls(name_en: str) -> str:
    q = quote_plus(name_en)
    payload = {
        "anilibria": f"https://www.anilibria.tv/search?find={q}",
        "animego": f"https://animego.org/search/all?q={q}",
        "jut_su": f"https://jut.su/anime/?q={q}",
        "shikimori": f"https://shikimori.one/animes?search={q}",
    }
    return json.dumps(payload, ensure_ascii=False)


def _build_description(name_ru: str, genres: str, year: int) -> str:
    human_genres = ", ".join(g.strip() for g in genres.split(","))
    return f"{name_ru} — популярное аниме {year} года в жанрах: {human_genres}."


def build_anime_data() -> list[dict]:
    seen = set()
    result = []
    for idx, (name_ru, name_en, year, genres) in enumerate(RAW_ANIME, start=1):
        key = name_en.strip().lower()
        if key in seen:
            continue
        seen.add(key)
        result.append(
            {
                "id": idx,
                "name_ru": name_ru,
                "name_en": name_en,
                "year": year,
                "description": _build_description(name_ru, genres, year),
                "genres": genres,
                "watch_urls": _make_watch_urls(name_en),
            }
        )
    return result


ANIME_DATA = build_anime_data()

QUOTES = [
    "Люди живут, чтобы быть счастливыми. — Юкино Миядзава",
    "Если проиграл, это не значит, что всё кончено. — Наруто Удзумаки",
    "Сила не в том, чтобы побеждать, а в том, чтобы не сдаваться. — Эдвард Элрик",
    "Человек умирает, когда его забывают. — Др. Хилулук",
    "Страх — это свобода. — Акира Фудо",
    "Только тот, кто готов к боли, способен на рост. — Канэки Кэн",
    "Иногда нужно потерять всё, чтобы понять ценность жизни. — Вайолет",
    "Чудеса случаются, когда ты действуешь. — Окабэ Ринтаро",
    "Сердце делает нас людьми. — Альфонс Элрик",
    "Даже в темноте есть путь вперёд. — Леви Аккерман",
]

MEMES = [
    "Когда сказал 'ещё одну серию' в 2:00 и уже 6:45.",
    "Составил план на день, но вышел новый сезон исекая.",
    "Ищу лёгкое аниме перед сном — включаю психологический триллер.",
    "Думал, что это филлер. Через 3 серии: 'где награды за боль?'",
    "Просто хотел проверить рейтинг, а начал марафон на 120 серий.",
]
